spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
#     根据entity更新表结构
      ddl-auto: none
#      输出sql语句在console和日志当中
    show-sql: true
logging:
  level:
    root: warn
    com.lvlei: debug
  file: log/blog-pro.log
server:
  port: 8081